-- 005_seed_more_career_roles.sql
-- 補上 18 個新職位 (對應 jobs_img/ 中尚未對應 CareerRole 的圖檔)
-- image_url 採用 Flutter assets 路徑 ('jobs_img/<file>.png')，與 lib/data/roles.dart 對齊。
-- 與 seed.sql 一致：on conflict 時會 update，安全可重跑。

insert into public.career_roles (id, title, tagline, image_url, skills, day_to_day, tags) values
  ('doctor_nurse', '醫師 / 護理師',
   '在病房或診間，把專業變成關懷',
   'jobs_img/doctor_nurse.png',
   array['臨床判斷','病史詢問','緊急處置','跨團隊協作','病人衛教'],
   array['看診','寫病歷','跟交班','照護病人','跟家屬溝通'],
   array['people']),
  ('teacher', '老師',
   '把知識變成可以被理解的語言',
   'jobs_img/teacher.png',
   array['備課','課程設計','評量設計','班級經營','家長溝通'],
   array['上課','改作業','開家長會','備課研究','處理學生情況'],
   array['people']),
  ('architect', '建築師',
   '把空間想像畫成可以蓋起來的圖',
   'jobs_img/architect.png',
   array['空間規劃','建築法規','BIM','跨專業協調','圖說溝通'],
   array['畫設計圖','跟業主討論','現場勘查','送審','監造'],
   array['engineering','design']),
  ('civil_servant', '公務員',
   '用制度與耐心把公共服務跑順',
   'jobs_img/civil_servant.png',
   array['法規熟悉','公文撰寫','跨單位協調','資料整理','流程改善'],
   array['處理民眾陳情','寫公文','開會','預算編列','業務查核'],
   array['people']),
  ('clerk', '店員 / 零售',
   '在第一線把服務做到位',
   'jobs_img/clerk.png',
   array['結帳收銀','商品熟悉','客戶應對','補貨整理','解決客訴'],
   array['收銀','理貨','清潔','回答顧客','處理退換貨'],
   array['sales']),
  ('content_creator', '自媒體創作者',
   '把腦中的點子變成被看見的內容',
   'jobs_img/content_creator.png',
   array['影音剪輯','腳本寫作','社群經營','數據分析','個人品牌'],
   array['企劃','拍攝','剪片','發文','看數據'],
   array['marketing']),
  ('factory_technician', '製造技術員',
   '讓生產線穩定地把東西做出來',
   'jobs_img/factory_technician.png',
   array['機械操作','製程理解','品管檢驗','SOP 執行','故障排除'],
   array['操作機台','量測','記錄產出','交接班','排除異常'],
   array['engineering']),
  ('farmer', '農夫',
   '用時間與土地換每一季的收成',
   'jobs_img/farmer.png',
   array['作物管理','灌溉','病蟲害判斷','機具操作','銷售規劃'],
   array['巡田','施肥','灌溉','採收','上市集／銷售'],
   array['people']),
  ('firefighter', '消防員',
   '在最緊急的時候站在第一線',
   'jobs_img/firefighter.png',
   array['火場救援','急救處置','體能訓練','器材操作','危機判斷'],
   array['訓練體能','器材保養','出勤救援','宣導講習','輪值待命'],
   array['people']),
  ('fitness', '健身教練',
   '陪人把身體變得更會用',
   'jobs_img/fitness.png',
   array['動作評估','訓練規劃','解剖學基礎','溝通激勵','飲食建議'],
   array['一對一指導','排訓練菜單','課表追蹤','社群經營','示範動作'],
   array['people']),
  ('flight_attendant', '空服員',
   '在三萬呎高空把服務做到位',
   'jobs_img/flight_attendant.png',
   array['客戶服務','安全程序','多語言','應急處理','團隊合作'],
   array['航前簡報','客艙服務','安全示範','處理客訴','航後檢查'],
   array['sales','people']),
  ('food_and_chef', '廚師',
   '用料理把心意端到客人面前',
   'jobs_img/food_and_chef.png',
   array['食材處理','刀工','火候掌握','菜單設計','成本控制'],
   array['備料','烹調','出菜','維持廚房整潔','研發新菜'],
   array['sales']),
  ('hairstylist', '美髮師',
   '用一把剪刀讓人變得更有自信',
   'jobs_img/hairstylist.png',
   array['剪髮技術','染燙','造型設計','顧客諮詢','色彩搭配'],
   array['洗剪燙染','造型設計','客戶諮詢','整理工具','社群分享作品'],
   array['design']),
  ('lawyer', '律師',
   '把複雜的情境翻成法律可處理的問題',
   'jobs_img/lawyer.png',
   array['法規查找','案件分析','文書撰寫','訴訟攻防','客戶諮詢'],
   array['寫狀','研讀法條','開庭','跟當事人討論','調解／談判'],
   array['finance']),
  ('living_pet', '寵物服務',
   '把專業耐心給不會講話的家人',
   'jobs_img/living_pet.png',
   array['動物行為','基礎醫療','美容修剪','急救處置','顧客溝通'],
   array['洗澡美容','遛狗','觀察健康','跟主人說明','清潔環境'],
   array['people']),
  ('performance_art', '表演藝術工作者',
   '在舞台上把情緒放大也收回',
   'jobs_img/performance_art.png',
   array['表演技巧','即興反應','身體控制','腳本理解','跨組合作'],
   array['排練','彩排','演出','跟導演對戲','體能/聲音訓練'],
   array['design']),
  ('reporter', '記者',
   '把現場發生的事，講成大家看得懂的故事',
   'jobs_img/reporter.png',
   array['採訪提問','即時報導','資料查證','文字撰寫','鏡頭表達'],
   array['追新聞','現場採訪','寫稿','錄影／錄音','上節目播報'],
   array['marketing']),
  ('spiritual_religion', '宗教與心靈服務',
   '陪人面對看不見的問題',
   'jobs_img/spiritual_religion.png',
   array['儀式執行','個案傾聽','經典／教義熟悉','活動籌辦','社群經營'],
   array['主持儀式','陪談','讀經','安排活動','服務信眾'],
   array['people'])
on conflict (id) do update set
  title      = excluded.title,
  tagline    = excluded.tagline,
  image_url  = excluded.image_url,
  skills     = excluded.skills,
  day_to_day = excluded.day_to_day,
  tags       = excluded.tags;

-- (可選) 同步既有 10 個職位的 image_url 從 'jobs/*.jpg' 換到 'jobs_img/*.png'
-- 若你希望 Supabase 跟 Flutter assets 路徑完全一致，可一併執行。
update public.career_roles set image_url = 'jobs_img/software_engineer.png'   where id = 'software_engineer';
update public.career_roles set image_url = 'jobs_img/data_analyst.png'        where id = 'data_analyst';
update public.career_roles set image_url = 'jobs_img/data_analyst.png'        where id = 'product_manager';
update public.career_roles set image_url = 'jobs_img/designer.png'            where id = 'uiux_designer';
update public.career_roles set image_url = 'jobs_img/marketing.png'           where id = 'digital_marketer';
update public.career_roles set image_url = 'jobs_img/marketing.png'           where id = 'sales';
update public.career_roles set image_url = 'jobs_img/marketing.png'           where id = 'customer_success';
update public.career_roles set image_url = 'jobs_img/marketing.png'           where id = 'hr';
update public.career_roles set image_url = 'jobs_img/finance_advisor.png'     where id = 'accountant';
update public.career_roles set image_url = 'jobs_img/software_engineer.png'   where id = 'cybersecurity_analyst';
